export const TOGGLE_SEARCH_TYPE_DROPDOWN = 'TOGGLE_SEARCH_TYPE_DROPDOWN';
export const SELECT_SEARCH_TYPE          = 'SELECT_SEARCH_TYPE';
export const TRANSLATE_SEARCH_TYPES      = 'TRANSLATE_SEARCH_TYPES';
